//
//  ChatroomPresenter.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChatroomPresentationLogic
{
  func presentSomething(response: Chatroom.Something.Response)
}

class ChatroomPresenter: ChatroomPresentationLogic
{
  weak var viewController: ChatroomDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Chatroom.Something.Response)
  {
    let viewModel = Chatroom.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
