//
//  ChatroomRouter.swift
//  words
//
//  Created by Neo Ighodaro on 01/01/2018.
//  Copyright (c) 2018 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ChatroomDataPassing {
    var dataStore: ChatroomDataStore? { get }
}

class ChatroomRouter: NSObject, ChatroomDataPassing {
    weak var viewController: ChatroomViewController?
    var dataStore: ChatroomDataStore?
}
