//
//  ChatroomPresenter.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol ChatroomPresentationLogic {
    func presentMessages(response: Chatroom.Messages.Fetch.Response)
    func toggleUserIsTyping(for name: String)
}

class ChatroomPresenter: ChatroomPresentationLogic {
    weak var viewController: ChatroomDisplayLogic?
    
    func presentMessages(response: Chatroom.Messages.Fetch.Response) {
        viewController?.displayChatMessages(response: response)
    }
    
    func toggleUserIsTyping(for name: String) {
        viewController?.handleTyping(by: name)
    }
}
