//
//  ChatroomModels.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import MessageKit
import PusherChatkit

enum Chatroom {

    struct Messages {
        
        // MARK: Fetch Messages
        
        struct Fetch {
            
            struct Request {
                var room: PCRoom
            }
            
            struct Response {
                var messages: [Message] = []
                
                init(messages: [PCMessage]) {
                    for message in messages {
                        let response = Chatroom.Messages.Create.Response(message: message)
                        self.messages.append(response.message)
                    }
                }
            }
        }
        
        // MARK: Create Messages
        
        struct Create {

            struct Request {
                var text: String
                var sender: Sender
                var room: PCRoom
            }
            
            struct Response {
                var message: Message
                
                init(message: PCMessage) {
                    self.message = Message(
                        text: message.text!,
                        sender: Sender(id: message.sender.id, displayName: message.sender.displayName),
                        messageId: String(describing: message.id),
                        date: ISO8601DateFormatter().date(from: message.createdAt)!
                    )
                }
            }
        }
    }
}
