//
//  MessageModels.swift
//  words
//
//  Created by Neo Ighodaro on 24/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Message
{
    var id: Int
    var room_id: String?
    var message: String
    var created_at: Date
}
