//
//  LoginInteractor.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func login(request: Login.Account.Request)
}

class LoginInteractor: LoginBusinessLogic {

    // MARK: Properties
    
    var viewController: LoginFormErrorLogic?
    var router: (NSObjectProtocol & LoginRoutingLogic)?
    var worker: UsersWorker = UsersWorker(usersStore: UsersAPI())

    // MARK: Login
    
    func login(request: Login.Account.Request) {
        self.worker.login(request: request) { token, error in
            guard error == nil else {
                self.viewController?.showValidationError("Error logging in.")
                return
            }

            self.router?.routeToListContacts()
        }
    }
}
