//
//  LoginWorker.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class LoginWorker
{
    func login(request: Login.Request, completion: @escaping (_ response: Login.Response) -> ())
    {
        let url: String = AppConstants.ENDPOINT + "/users/login"
        
        let params: Parameters = [
            "email": request.email,
            "password": request.password
        ]
        
        Alamofire
            .request(url, method: .post, parameters: params)
            .validate()
            .responseJSON { response in
                switch (response.result) {
                case .success(let data):
                    let data = data as! [String: Any?]
                    let res = Login.Response(successful: true, data: data)
                    completion(res)
                case .failure(_):
                    let res = Login.Response(successful: false)
                    completion(res)
                }
            }
    }
}
