//
//  LoginInteractor.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func login(request: Login.Request)
}

class LoginInteractor: LoginBusinessLogic
{
    var worker: LoginWorker?
    
    var viewController: LoginFormErrorLogic?
    
    var router: (NSObjectProtocol & LoginRoutingLogic)?
    
    // MARK: Login
    
    func login(request: Login.Request) {
        worker = LoginWorker()
        
        worker?.login(request: request, completion: { response in
            if response.successful {
                TokenDataStore().setToken(response.token!)
                
                self.router?.routeToListMessages()
            } else {
                self.viewController?.showValidationError("Invalid username or password.")
            }
        })
    }
}
