//
//  LoginModels.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    struct Request
    {
        var email: String
        var password: String
    }
    
    struct Response
    {
        var successful: Bool
        var ID: Int?
        var email: String?
        var token: [String : Any?]?
        var data: [String: Any?]?
        
        init(successful: Bool) {
            self.successful = successful
        }
        
        init(successful: Bool, data: [String:Any?]?) {
            self.data = data
            self.successful = successful
            
            self.ID = data!["id"] as? Int
            self.email = data!["email"] as? String
            self.token = data!["token"] as? [String : Any?]
        }
    }
}
