//
//  LoginModels.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    struct Account
    {
        struct Request
        {
            var email: String
            var password: String
        }
        
        struct Response
        {
            var userToken: UserToken?
            var data: [String: Any?]?
            
            init(data: [String:Any?]?) {
                self.data = data
                
                self.userToken = UserToken(
                    token_type: (data!["token_type"] as? String)!,
                    access_token: (data!["access_token"] as? String)!,
                    refresh_token: (data!["refresh_token"] as? String)!,
                    expires_in: (data!["expires_in"] as? Int)!
                )
            }
        }
    }

    struct Chatkit
    {
        struct Request
        {
            var username: String
            var password: String
            var token: UserToken
        }
        
        struct Response
        {
            var token: ChatkitToken?
            var data: [String:Any?]
            
            init(data: [String:Any?]) {
                self.data = data
                self.token = ChatkitToken(
                    access_token: data["access_token"] as? String,
                    refresh_token: data["refresh_token"] as? String
                )
            }
        }
    }
}
