//
//  SignupInteractor.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupBusinessLogic
{
    func createAccount(request: Signup.Request)
}

class SignupInteractor: SignupBusinessLogic
{
    var worker: SignupWorker?
    
    var viewController: SignupFormErrorLogic?

    var router: (NSObjectProtocol & SignupRoutingLogic)?
    
    // MARK: Create Account
    
    func createAccount(request: Signup.Request) {
        worker = SignupWorker()
        
        worker?.createAccount(request: request, completion: { response in
            if response.successful {
                TokenDataStore().setToken(response.token!)

                self.router?.routeToListMessages()
            } else {
                self.viewController?.showValidationError("Cannot create account, try again later.")
            }
        })
    }
}
