//
//  SignupInteractor.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupBusinessLogic {
    func createAccount(request: Signup.Request)
}

class SignupInteractor: SignupBusinessLogic {
    
    // MARK: Properties
    
    var viewController: SignupFormErrorLogic?
    var router: (NSObjectProtocol & SignupRoutingLogic)?
    var worker: UsersWorker = UsersWorker(usersStore: UsersAPI())

    // MARK: Create Account
    
    func createAccount(request: Signup.Request) -> Void {
        self.worker.signup(request: request) { (user, signupError) in
            if signupError == nil {
                self.router?.routeToListMessages()
            } else {
                self.viewController?.showValidationError("Unable to create account, try again later!")
            }
        }
    }
}
