//
//  SignupRouter.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SignupRoutingLogic {
    func routeToListMessages()
}

class SignupRouter: NSObject, SignupRoutingLogic {
    
    weak var viewController: SignupViewController?
    
    func routeToListMessages() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MainNavigator") as! UINavigationController
        
        viewController!.show(destinationVC, sender: nil)
    }
}
