//
//  SignupModels.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Signup
{
    struct Request
    {
        var name: String
        var email: String
        var password: String
    }

    struct Response
    {
        var user: User?
        var data: [String : Any?]?
        
        init(data: [String:Any?]?) {
            self.data = data
            
            self.user = User(
                id: (data!["id"] as? Int)!,
                name: (data!["name"] as? String)!,
                email: (data!["email"] as? String)!,
                chatkit_id: (data!["chatkit_id"] as? String)!
            )
        }
    }
}
