//
//  ListMessagesPresenter.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMessagesPresentationLogic
{
     func presentFetchedMessages(response: ListMessages.FetchMessages.Response)
}

class ListMessagesPresenter: ListMessagesPresentationLogic
{
    weak var viewController: ListMessagesDisplayLogic?
    
    func presentFetchedMessages(response: ListMessages.FetchMessages.Response) {
        var displayedMessages: [ListMessages.FetchMessages.ViewModel.DisplayedMessage] = []
        
        for message in response.messages {
            let displayedMessage = ListMessages.FetchMessages.ViewModel.DisplayedMessage(
                id: message.id,
                message: message.message,
                room_id: message.room_id!
            )

            displayedMessages.append(displayedMessage)
        }

        let viewModel = ListMessages.FetchMessages.ViewModel(displayedMessages: displayedMessages)
        
        viewController?.displayFetchedMessages(viewModel: viewModel)
    }
}
