//
//  ListMessagesInteractor.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMessagesBusinessLogic
{
  func doSomething(request: ListMessages.Something.Request)
}

protocol ListMessagesDataStore
{
    var account: [String : Any?] { get set }
}

class ListMessagesInteractor: ListMessagesBusinessLogic, ListMessagesDataStore
{
    var account: [String : Any?] = [:]
    
  var presenter: ListMessagesPresentationLogic?
  var worker: ListMessagesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListMessages.Something.Request)
  {
    worker = ListMessagesWorker()
    worker?.doSomeWork()
    
    let response = ListMessages.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
