//
//  ListMessagesModels.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMessages
{
    // MARK: Use cases
  
    enum FetchMessages
    {
        struct Request
        {
        }
        
        struct Response
        {
            var messages: [Message]
        }
        
        struct ViewModel
        {
            struct DisplayedMessage
            {
                var id: Int
                var message: String
                var room_id: String
            }

            var displayedMessages: [DisplayedMessage]
        }
    }
}
