//
//  WelcomeViewController.swift
//  words
//
//  Created by Neo Ighodaro on 21/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WelcomeViewController: UIViewController
{
    // Nothing really happens here tbh!
}
