//
//  ListContactsInteractor.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactsBusinessLogic
{
  func doSomething(request: ListContacts.Something.Request)
}

protocol ListContactsDataStore
{
  //var name: String { get set }
}

class ListContactsInteractor: ListContactsBusinessLogic, ListContactsDataStore
{
  var presenter: ListContactsPresentationLogic?
  var worker: ListContactsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ListContacts.Something.Request)
  {
    worker = ListContactsWorker()
    worker?.doSomeWork()
    
    let response = ListContacts.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
