//
//  ListContactsRouter.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListContactsRoutingLogic {
    func routeToChatroom(segue: UIStoryboardSegue)
}

protocol ListContactsDataPassing {
    var dataStore: ListContactsDataStore? { get }
}

class ListContactsRouter: NSObject, ListContactsRoutingLogic, ListContactsDataPassing {

    // MARK: Properties
    
    var dataStore: ListContactsDataStore?
    weak var viewController: ListContactsViewController?

    // MARK: Routing
    
    func routeToChatroom(segue: UIStoryboardSegue) {
        let destinationVC = segue.destination as! ChatroomViewController
        var destinationDS = destinationVC.router!.dataStore!
            
        passDataToChatroom(source: dataStore!, destination: &destinationDS)
    }

    // MARK: Passing data
    
    func passDataToChatroom(source: ListContactsDataStore, destination: inout ChatroomDataStore) {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.contact = source.contacts?[selectedRow!]
        destination.currentUser = source.currentUser
    }
}
