//
//  ListContactsPresenter.swift
//  words
//
//  Created by Neo Ighodaro on 09/12/2017.
//  Copyright (c) 2017 CreativityKills Co.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListContactsPresentationLogic
{
  func presentSomething(response: ListContacts.Something.Response)
}

class ListContactsPresenter: ListContactsPresentationLogic
{
  weak var viewController: ListContactsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ListContacts.Something.Response)
  {
    let viewModel = ListContacts.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
